spring:
  datasource:
    url: ?????
    username: ?????
    password: ?????
    driver-class-name: org.postgresql.Driver
jwt:
  secret: ?????
  accessTokenExpiration: 3600000
  refreshTokenExpiration: 1209600000